#!/usr/bin/env python3
"""Inline every stylesheet and script from index.html into one preview file.

The multi-file project stays the source of truth. Run this whenever you want a
single file to open, email or drop onto a USB stick for the booth laptop.

    python3 build-preview.py
"""

import base64
import re
import pathlib

ROOT = pathlib.Path(__file__).parent
SOURCE = ROOT / "index.html"
TARGET = ROOT / "preview-single-file.html"


def read(rel_path):
    return (ROOT / rel_path).read_text(encoding="utf-8")


def inline_styles(html):
    def swap(match):
        href = match.group(1)
        return "<style>\n/* {0} */\n{1}\n</style>".format(href, read(href))

    return re.sub(r'<link rel="stylesheet" href="([^"]+)">', swap, html)


def inline_scripts(html):
    def swap(match):
        src = match.group(1)
        return "<script>\n/* {0} */\n{1}\n</script>".format(src, read(src))

    return re.sub(r'<script src="([^"]+)"></script>', swap, html)


def inline_favicon(html):
    svg = base64.b64encode(read("assets/favicon.svg").encode("utf-8")).decode("ascii")
    return html.replace(
        '<link rel="icon" href="assets/favicon.svg" type="image/svg+xml">',
        '<link rel="icon" href="data:image/svg+xml;base64,{0}" type="image/svg+xml">'.format(svg),
    )


def main():
    html = SOURCE.read_text(encoding="utf-8")
    html = inline_styles(html)
    html = inline_scripts(html)
    html = inline_favicon(html)
    html = html.replace(
        "<!DOCTYPE html>",
        "<!DOCTYPE html>\n<!-- Generated by build-preview.py. Do not edit by hand. "
        "Edit the files under css/ and js/, then run the script again. -->",
    )
    TARGET.write_text(html, encoding="utf-8")
    print("Wrote {0} ({1:,} bytes)".format(TARGET.name, TARGET.stat().st_size))


if __name__ == "__main__":
    main()
