import { readFile, writeFile } from 'node:fs/promises';

// Node equivalent of build-preview.py for environments without Python.
const root = new URL('../', import.meta.url);
let html = await readFile(new URL('index.html', root), 'utf8');
for (const match of [...html.matchAll(/<link rel="stylesheet" href="([^"]+)">/g)]) {
  const css = await readFile(new URL(match[1], root), 'utf8');
  html = html.replace(match[0], () => `<style>\n/* ${match[1]} */\n${css}\n</style>`);
}
for (const match of [...html.matchAll(/<script src="([^"]+)"><\/script>/g)]) {
  const js = await readFile(new URL(match[1], root), 'utf8');
  html = html.replace(match[0], () => `<script>\n/* ${match[1]} */\n${js}\n</script>`);
}
const favicon = (await readFile(new URL('assets/favicon.svg', root))).toString('base64');
for (const match of [...html.matchAll(/<(?:img|image)\b[^>]*\b(?:src|href)="(assets\/[^\"]+)"[^>]*>/g)]) {
  const bytes = await readFile(new URL(match[1], root));
  const mime = match[1].endsWith('.svg') ? 'image/svg+xml' : 'image/png';
  html = html.replace(match[0], () => match[0].replace(match[1], `data:${mime};base64,${bytes.toString('base64')}`));
}
html = html.replace('<link rel="icon" href="assets/favicon.svg" type="image/svg+xml">', `<link rel="icon" href="data:image/svg+xml;base64,${favicon}" type="image/svg+xml">`);
html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by scripts/build-preview.mjs. Do not edit by hand. Edit the files under css/ and js/, then run npm run build:preview. -->');
await writeFile(new URL('preview-single-file.html', root), html);
console.log(`Wrote preview-single-file.html (${Buffer.byteLength(html).toLocaleString()} bytes)`);
